<#
.SYNOPSIS
Generate a single operator credential sheet from live Terraform state.

.DESCRIPTION
Every value here already exists in Terraform state or SSM. This writes them to
one file so an operator does not have to remember which of six commands
produces which secret.

It is GENERATED, never hand-edited: the Keycloak host is replaced by any
user_data change, the console and API move if the distributions or gateways are
rebuilt, and passwords change on rotation. Re-run it instead of correcting it.

The output matches *.local.md in .gitignore and holds plaintext secrets. Do not
commit it, and do not paste it into an issue, a chat or a screenshot.

    .\scripts\credentials-sheet.ps1                 -> CREDENTIALS.local.md
    .\scripts\credentials-sheet.ps1 -Path other.md
#>
[CmdletBinding()]
param(
  [string]$Path = 'CREDENTIALS.local.md',
  [string]$Region = $(if ($env:TF_VAR_region) { $env:TF_VAR_region } else { 'eu-central-1' })
)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$App = Join-Path $Root 'infrastructure/aws'

foreach ($tool in 'aws', 'terraform') {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { throw "$tool is required and is not on PATH." }
}

Write-Host '==> Reading Terraform state'
$tf = terraform "-chdir=$App" output -json | ConvertFrom-Json
function Out-Value([string]$Name) {
  $p = $tf.PSObject.Properties[$Name]
  if ($p) { return [string]$p.Value.value }
  return ''
}

# The SSM path is the stack prefix, which the Name tag carries: "ti-student"
# from "ti-student-keycloak". Parenthesised because `Out-Value 'x' -replace ...`
# binds -replace as a parameter of Out-Value rather than as an operator.
$prefix = ((Out-Value 'keycloak_name_tag') -replace '-keycloak$', '')

Write-Host '==> Reading SSM'
function Get-Parameter([string]$Name) {
  $v = aws ssm get-parameter --region $Region --name $Name --with-decryption --query 'Parameter.Value' --output text 2>$null
  if ($LASTEXITCODE -ne 0 -or -not $v) { return '(not set)' }
  return $v.Trim()
}
$aiKey = Get-Parameter "/$prefix/ai-api-key"
$smtpPassword = Get-Parameter "/$prefix/smtp-password"

Write-Host '==> Reading the deployed AI settings'
$apiFn = Out-Value 'api_function_name'
$env_ = aws lambda get-function-configuration --function-name $apiFn --region $Region --query 'Environment.Variables' --output json | ConvertFrom-Json
$smtpUser = ''
$tfvars = Join-Path $App 'terraform.tfvars'
if (Test-Path $tfvars) {
  $m = Select-String -Path $tfvars -Pattern '^\s*smtp_username\s*=\s*"(.+)"' | Select-Object -First 1
  if ($m) { $smtpUser = $m.Matches[0].Groups[1].Value }
  $mf = Select-String -Path $tfvars -Pattern '^\s*smtp_from\s*=\s*"(.+)"' | Select-Object -First 1
  $smtpFrom = if ($mf) { $mf.Matches[0].Groups[1].Value } else { '(not set)' }
  $mh = Select-String -Path $tfvars -Pattern '^\s*smtp_host\s*=\s*"(.+)"' | Select-Object -First 1
  $smtpHost = if ($mh) { $mh.Matches[0].Groups[1].Value } else { '(not set)' }
}

$generated = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss K')
$account = aws sts get-caller-identity --query Account --output text

$md = @"
# Credentials and endpoints

> **Generated $generated by ``scripts/credentials-sheet.ps1``. Do not commit, do
> not paste anywhere.** Matched by ``*.local.md`` in .gitignore. Re-run the
> script rather than editing this file: the Keycloak host is replaced by any
> user_data change and several values move with it.

AWS account ``$account`` · region ``$Region`` · prefix ``$prefix``

## Open these

| | |
| --- | --- |
| Console | $(Out-Value 'console_url') |
| API (Swagger at /docs, needs a token) | $(Out-Value 'api_url') |
| Assistant | $(Out-Value 'assistant_url') |
| Keycloak | $(Out-Value 'keycloak_url') |
| GitHub Actions | https://github.com/divinecodes1/Transfer-and-Conversion-Intelligence-Platform/actions |

Public health probes, no credential required: ``/healthz`` on the API and the
assistant. ``/health`` is entitlement-scoped and refuses anonymous callers by
design.

## Sign in to the console

Self-registration is **disabled**. Accounts are created in Keycloak by hand.

| Username | Password | Role | Sees |
| --- | --- | --- | --- |
| ``admin.demo`` | ``TransferDemo1!`` | PLATFORM_ADMIN | every portfolio |
| ``analyst.demo`` | ``TransferDemo1!`` | TRANSFER_ANALYST | every portfolio |
| ``manager.auto`` | ``TransferDemo1!`` | TRANSFER_MANAGER | PF_AUTO only |
| ``manager.power`` | ``TransferDemo1!`` | TRANSFER_MANAGER | PF_POWER only |
| ``viewer.demo`` | ``TransferDemo1!`` | TRANSFER_VIEWER | PF_IOT only |
| ``parth.goswami838@gmail.com`` | *(set at registration)* | PLATFORM_ADMIN | every portfolio |

These five are fixture accounts committed in ``keycloak/realm-export.json`` and
are not secret. The scope differences are enforced by PostgreSQL row-level
security, not by the console hiding screens.

## Keycloak administration

| | |
| --- | --- |
| URL | $(Out-Value 'keycloak_url') |
| Realm | ``master`` (not ``transferops``) |
| Username | ``$(Out-Value 'keycloak_admin_username')`` |
| Password | ``$(Out-Value 'keycloak_admin_password')`` |
| Host instance | ``$(Out-Value 'keycloak_instance_id')`` (tag ``$(Out-Value 'keycloak_name_tag')``) |

Shell on the host without SSH: ``aws ssm start-session --target $(Out-Value 'keycloak_instance_id')``

## Database

Private. No public ingress; reachable only from inside the VPC.

| | |
| --- | --- |
| Endpoint | ``$(Out-Value 'database_endpoint')`` |
| Master user | ``$(Out-Value 'database_username')`` |
| Master password | ``$(Out-Value 'database_password')`` |
| Reader password | ``$(Out-Value 'reader_password')`` |
| Auditor password | ``$(Out-Value 'auditor_password')`` |
| AI writer password | ``$(Out-Value 'ai_password')`` |

## Mail (Amazon SES)

| | |
| --- | --- |
| Host / port | ``$smtpHost`` : 587, STARTTLS |
| From | ``$smtpFrom`` |
| SMTP username | ``$smtpUser`` |
| SMTP password | ``$smtpPassword`` |

**Sandbox**: SES delivers only to verified identities. Production access was
requested and denied (case ``178667304600071``); with self-registration off this
does not matter, since mail only goes to accounts you create.

## AI provider

| | |
| --- | --- |
| Provider | ``$($env_.TRANSFEROPS_AI_PROVIDER)`` |
| Model | ``$($env_.TRANSFEROPS_AI_MODEL)`` |
| Base URL | ``$($env_.TRANSFEROPS_AI_BASE_URL)`` |
| API key | ``$aiKey`` |
| Daily call cap | ``$($env_.TRANSFEROPS_AI_DAILY_CAP)`` |

## Deployment plumbing

| | |
| --- | --- |
| CI role | ``$(Out-Value 'github_actions_role_arn')`` |
| ECR (API) | ``$(Out-Value 'ecr_api_repository')`` |
| ECR (Keycloak) | ``$(Out-Value 'ecr_keycloak_repository')`` |
| Console bucket | ``$(Out-Value 'console_bucket')`` |
| CloudFront (console) | ``$(Out-Value 'cloudfront_distribution_id')`` |
| Documents bucket | ``$(Out-Value 'documents_bucket')`` |
| Lambdas | ``$(Out-Value 'api_function_name')`` · ``$(Out-Value 'assistant_function_name')`` · ``$(Out-Value 'refresh_function_name')`` |
| SSM documents | ``$(Out-Value 'keycloak_rollout_document')`` · ``$(Out-Value 'warehouse_seed_document')`` |

## Commands worth keeping

``````powershell
# every terraform run must go through this, or empty variables destroy the
# AI key and the SMTP password without failing
.\scripts\tf-apply.ps1 -auto-approve

# republish CI secrets and variables after any apply that moved something
.\scripts\setup-github-actions.ps1

# deploy everything and verify all three tiers
gh workflow run deploy.yml

# reload the warehouse and re-grant the operator
gh workflow run deploy.yml -f seed_warehouse=true

# regenerate this sheet
.\scripts\credentials-sheet.ps1
``````

## Rotation

Secrets live in SSM under ``/$prefix/``. Rotate by exporting the new value and
re-applying; the parameter and every consumer follow.

``````powershell
`$env:TF_VAR_ai_api_key    = 'sk-...'
`$env:TF_VAR_smtp_password = '...'
.\scripts\tf-apply.ps1 -auto-approve
``````
"@

$target = if ([IO.Path]::IsPathRooted($Path)) { $Path } else { Join-Path $Root $Path }
[IO.File]::WriteAllText($target, $md, [Text.UTF8Encoding]::new($false))
Write-Host "`nWrote $target"
Write-Host 'Contains live secrets in plaintext. Gitignored via *.local.md -- keep it that way.'
